//
//  OCSoundContainer.swift
//  Get REKT Soundboard
//
//  Created by Jared Ebenstein on 8/1/16.
//
//

//This magical class contains *hardcoded* arrays for each page which store info for each sound file

//Programming theme song: Spag Heddy & EH!DE - Better
//https://www.youtube.com/watch?v=-cjyNYuvNh4
import Foundation
import UIKit

class Sound {
    var labelText: String
    var soundResourceName: String
    var iconResourceName: String
    var isFavorite: Bool
    
    var id = 0
    
//    static func findById (id: Int) -> Sound? {
//        //Sound ID's are offset by 14
//        let pages = soundContainers
//        var foundSound : Sound?
//        for page in pages {
//            for sound in page {
//                if sound.id == id {
//                    foundSound = sound
//                }
//            }//end page
//        }//end pages
//
//        return foundSound
//    }
    
    static func getListOfSoundIdentifiersFor(page: Int) -> [Sound?] {
        // 0..14
        // 15..29
        // 30..44
        // etc
        
        let start = 0 + 15 * page // pages start at 0 and and at (sounds.count / 15)
        let end = start + 14
        var soundList = [Sound?]()
        for i in start...end {
            if (i > sounds.count - 1) {
                break
            }
            soundList.append(sounds[i])
        }
        return soundList
    }
    // static func getSoundListForPage
    // returns an array of 15 sounds for page N
    
    init(labelText: String, soundResourceName: String, iconResourceName: String, isFavorite: Bool) {
        self.labelText = labelText
        self.soundResourceName = soundResourceName
        self.iconResourceName = iconResourceName
        self.isFavorite = isFavorite
    }
}

//Begin making sound pages using Swift's magic global variables

//var pageOne = [SingleSound(labelText: "One", soundResourceName: "test", iconResourceName: "pine"),
//    SingleSound(labelText: "Two", soundResourceName: "test", iconResourceName: "pine"),
//    SingleSound(labelText: "Three", soundResourceName:"test", iconResourceName: "pine"),
//    SingleSound(labelText: "Four", soundResourceName: "test", iconResourceName: "pine"),
//    SingleSound(labelText: "Five", soundResourceName:"test", iconResourceName: "pine")]
//add damn son where'd you find this

var sounds = [
    Sound(labelText: "xX_N4TH4N_Xx", soundResourceName: "Goddammit Nathan.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "Watcha Say", soundResourceName: "Watcha Say.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "WOMBO COMBO", soundResourceName: "WOMBO COMBO! WHERE ARE YOU AT.mp3", iconResourceName: "MLG", isFavorite: false),
    Sound(labelText: "HITM4RK3R", soundResourceName: "HITMARKER.mp3", iconResourceName: "Hitmarker", isFavorite: false),
    Sound(labelText: "Wow ;)", soundResourceName: "Eddy Wally wow meme.mp3", iconResourceName: "Wow", isFavorite: false),
    Sound(labelText: "Where'd You Find This", soundResourceName: "DAMN SON! WHERED YOU FIND THIS.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "Sike", soundResourceName: "Sike that's the wrong number.mp3", iconResourceName: "Rap Battle", isFavorite: false),
    Sound(labelText: "Reaction", soundResourceName: "Epic Rap Crowd Reaction.mp3", iconResourceName: "Rap Battle", isFavorite: false),
    Sound(labelText: "Wow Effect", soundResourceName: "DAMN SON WOW.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "OH BABY A TRIPLE", soundResourceName: "ohbabyatriple.mp3", iconResourceName: "MLG", isFavorite: false),
    Sound(labelText: "Trickshot 1", soundResourceName: "Halo Scream.mp3", iconResourceName: "MLG", isFavorite: false),
    Sound(labelText: "Trickshot 2", soundResourceName: "trickshot.mp3", iconResourceName: "MLG", isFavorite: false),
    Sound(labelText: "MLG Horn", soundResourceName: "MLG HORNS 2.mp3", iconResourceName: "Airhorn", isFavorite: false),
    Sound(labelText: "MLG Illuminati", soundResourceName: "Air Horn Illuminati Confirmed Sound Effect.mp3", iconResourceName: "Illuminati", isFavorite: false),
    Sound(labelText: "Air Horn", soundResourceName: "_MLG SOURCE_ Air Horn Sound.mp3", iconResourceName: "Airhorn", isFavorite: false),
    Sound(labelText: "I'm gonna get you boy!", soundResourceName: "Im gonna get ya boy.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "SANIC", soundResourceName: "SANIC.mp3", iconResourceName:  "Sanic", isFavorite: false),
    Sound(labelText: "Trombone", soundResourceName: "SAD TROMBONE.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Trickshot", soundResourceName: "EpicTrickshotReaction2.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Dramatic Music", soundResourceName: "DRAMATIC.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "2SAD4ME", soundResourceName: "2SAD4ME.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Airhorn Sonata", soundResourceName: "AIRHORN SONATA.mp3", iconResourceName:  "Airhorn", isFavorite: false),
    Sound(labelText: "2SAD4MEMLG", soundResourceName: "2SAD4MEMLG.mp3", iconResourceName:  "Airhorn", isFavorite: false),
    Sound(labelText: "Shut up", soundResourceName: "Stfu you cunt!.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Get Rekt", soundResourceName: "getrekt.m4a", iconResourceName:  "Get Rekt.jpg", isFavorite: false),
    Sound(labelText: "Darude Dankstorm", soundResourceName: "darudedankstorm.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "Get Noscoped", soundResourceName: "GET NOSCOPED.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "My hope will never die", soundResourceName: "hopewillneverdie.m4a", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Surprise", soundResourceName: "Suprise.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Never done that", soundResourceName: "neverdonethat.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Illuminati Confirmed", soundResourceName: "Illuminati Confirmed.mp3", iconResourceName:  "Illuminati", isFavorite: false),
    Sound(labelText: "Cry", soundResourceName: "Cry.mp3", iconResourceName:  "CryingFace", isFavorite: false),
    Sound(labelText: "50 States", soundResourceName: "illuminaticonfirmed.mp3", iconResourceName:  "Illuminati", isFavorite: false),
    Sound(labelText: "OMG", soundResourceName: "ohmygod.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "OMG TRICKSHOT", soundResourceName: "omgtrickshot.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "FaZe Clan", soundResourceName: "opticfazeclan.mp3", iconResourceName:  "Faze2", isFavorite: false),
    Sound(labelText: "Shots Fired!", soundResourceName: "shotsfired.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Tactical Nuke", soundResourceName: "tacticalnuke.mp3", iconResourceName:  "Radiation", isFavorite: false),
    Sound(labelText: "2MLG4ME", soundResourceName: "2mlg4me.m4a", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Love", soundResourceName: "shrekislove.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "FHRITP", soundResourceName: "Fuck her right in the pussy sound effect.mp3", iconResourceName:  "FHRITP", isFavorite: false),
    Sound(labelText: "Swagsc0pe", soundResourceName: "360swagscope.m4a", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Blaze it", soundResourceName: "420blazeit.m4a", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "%@$# you", soundResourceName: "Fuck you!.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Punch", soundResourceName: "punch.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "I Can't See S@#%", soundResourceName: "icantseeshit.mp3", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "No Hug 4 U", soundResourceName: "nohug4u.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "Swedish", soundResourceName: "swedish.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "Sneeze", soundResourceName: "sneeze.mp3", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "PewDiePie", soundResourceName: "pewdiepie.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "You Shall Not Pass", soundResourceName: "youshallnotpass.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "Detotated Wam", soundResourceName: "DEDOTADED WAM.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Mom get the camera!", soundResourceName: "MOM GET THE CAMERA.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "Gotcha", soundResourceName: "GOTCHA BIACH.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "gr8 m8", soundResourceName: "Gr8b8m8.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Math", soundResourceName: "mathilluminati.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Intervention", soundResourceName: "intervention.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Scream", soundResourceName: "Random Male Scream.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Duck", soundResourceName: "duck.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "Freakout", soundResourceName: "freakout2.m4a", iconResourceName:  "PewDiePie", isFavorite: false),
    Sound(labelText: "Deal with it", soundResourceName: "Deal With it.mp3", iconResourceName:  "MLG2", isFavorite: false),
    Sound(labelText: "REKT", soundResourceName: "quickscoped.mp3", iconResourceName:  "MLG2", isFavorite: false),
    Sound(labelText: "Gotta Go Fast!", soundResourceName: "Gotta Go Fast! (NEW) .mp3", iconResourceName:  "Sanic", isFavorite: false),
    Sound(labelText: "Hitmarker Spam", soundResourceName: "Hitmarker Spam (NEW).mp3", iconResourceName:  "Hitmarker", isFavorite: false),
    Sound(labelText: "21", soundResourceName: "21 - MLG Sound Effect (HD).mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Oh No!", soundResourceName: "fail.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Boom!", soundResourceName: "Boom.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "Bam!", soundResourceName: "Bam.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "Bop!", soundResourceName: "Bop.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "Bada Bap Boomp", soundResourceName: "BadaBap.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "Pow!", soundResourceName: "Pow.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "OOO", soundResourceName: "OOO.mp3", iconResourceName:  "Rap Battle", isFavorite: false),
    Sound(labelText: "Deez Nuts!", soundResourceName: "Nuts.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Deez Nuts! (Full)", soundResourceName: "FULL NUTZ.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "HA! Got em!", soundResourceName: "HA!.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Mail!", soundResourceName: "Something Came in the Mail Today.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Chickens", soundResourceName: "Chickens.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Crack Kid!", soundResourceName: "Crack Kid.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Allahu Akbar!", soundResourceName: "Allahu Akbar.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "LeBron #1", soundResourceName: "Little Copy.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "LeBron #2", soundResourceName: "Asian Lebron.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Are You 5?", soundResourceName: "Are You 5?.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Bruh", soundResourceName: "Bruh.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "HA! Gay!", soundResourceName: "Ha! Gay.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "My Name is Jeff", soundResourceName: "My Name Is jeff.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Yas", soundResourceName: "Yass.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Yee", soundResourceName: "Yee.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Rage", soundResourceName: "Mark Rage.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "I hate everything!", soundResourceName: "I Hate EVERYTHING.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "I don't want to play", soundResourceName: "I don't want to play this.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "Car", soundResourceName: "car.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Get Out Me Car!", soundResourceName: "GetOut.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Jet Fuel", soundResourceName: "Jet Fuel Can't Melt Steel Beams.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "You're not my Dad", soundResourceName: "NotMyDad.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "One Question", soundResourceName: "OneQuestion.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "What are THOSE?", soundResourceName: "WhatAreThose.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Weed Engine", soundResourceName: "WeedEngine.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Spooky Scary Skeletons", soundResourceName: "SpookyScarySkeletons.mp3", iconResourceName:  "Spooky", isFavorite: false),
    Sound(labelText: "Banana Bus", soundResourceName: "BananaBus.mp3", iconResourceName:  "VanossGaming", isFavorite: false),
    Sound(labelText: "DDoS", soundResourceName: "DDOS.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Nice Meme", soundResourceName: "Nice Meme.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Finish Him!", soundResourceName: "FinishHim.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Leeroy Jenkins", soundResourceName: "Leeroy.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Over 9000", soundResourceName: "9000.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "American History", soundResourceName: "AmericanHistory.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "Beautiful", soundResourceName: "Beautiful.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Watermelon", soundResourceName: "Watermelon.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Watermelon Full", soundResourceName: "Full melons.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "S@#%", soundResourceName: "FFShit.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Why did you leave me?", soundResourceName: "FFLeaveMe.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Kobe", soundResourceName: "Kobe.mp3", iconResourceName:  "VanossGaming", isFavorite: false),
    Sound(labelText: "Noice.mp5", soundResourceName: "Noice.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Derp.jpg", soundResourceName: "retarded batman.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Spodermen", soundResourceName: "Spodermen.mp3", iconResourceName:  "Spodermen", isFavorite: false),
    Sound(labelText: "Look at this!", soundResourceName: "Look at this.mp3", iconResourceName:  "Orton", isFavorite: false),
    Sound(labelText: "Massive RKO!", soundResourceName: "MassiveRKO.mp3", iconResourceName:  "Orton", isFavorite: false),
    Sound(labelText: "Never Seen", soundResourceName: "never seen.mp3", iconResourceName:  "Orton", isFavorite: false),
    Sound(labelText: "Slithering Outta Nowhere", soundResourceName: "Slither.mp3", iconResourceName:  "Orton", isFavorite: false),
    Sound(labelText: "John Cena Prank Call", soundResourceName: "John Cena Prank Call.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Scream", soundResourceName: "ScreamingMerkKid.mp3", iconResourceName:  "MerkMusic", isFavorite: false),
    Sound(labelText: "CHIPOTLE", soundResourceName: "Chipotle.mp3", iconResourceName:  "VanossGaming", isFavorite: false),
    Sound(labelText: "HOODINI", soundResourceName: "HOODINI.mp3", iconResourceName:  "VanossGaming", isFavorite: false),
    Sound(labelText: "Idiot", soundResourceName: "IDIOT.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "You Won!", soundResourceName: "YouWon.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Fatality", soundResourceName: "Fatality.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "s/o to pear", soundResourceName: "PEAR.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "And his name is...", soundResourceName: "AndHisNameIsJohnCena.mp3", iconResourceName:  "Cena", isFavorite: false),
    Sound(labelText: "JOHN CENA (long)", soundResourceName: "JohnCenaFullLong.mp3", iconResourceName:  "Cena", isFavorite: false),
    Sound(labelText: "Cena (Dank)", soundResourceName: "JohnCenaDankJustName.mp3", iconResourceName:  "Cena", isFavorite: false),
    Sound(labelText: "John Cena Theme", soundResourceName: "CenaMusic.mp3", iconResourceName:  "Cena", isFavorite: false),
    Sound(labelText: "It's All Ogre", soundResourceName: "AllOgre.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Bond with me", soundResourceName: "BondWithMeJimmy.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "This is My Swamp (long)", soundResourceName: "HeWhispers.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "This is My Swamp", soundResourceName: "ThisIsMySwamp.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "The Pizza is Aggressive", soundResourceName: "ThePizzaIsAggressive.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "21!", soundResourceName: "FF21.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "I'm a Lemon", soundResourceName: "ImALemon.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "I'm a Lemon (Song)", soundResourceName: "FFLemonSong.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Scream", soundResourceName: "FFScreamLemon.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Ravioli", soundResourceName: "WhatsInThePocket.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Just a Prank", soundResourceName: "JustAPrank.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Another Scream", soundResourceName: "AnotherScream.mp3", iconResourceName:  "MLG", isFavorite: false),
    Sound(labelText: "What is going on here?", soundResourceName: "WhatIsGoingOnHere.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Breakfast!", soundResourceName: "Breakfast.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Great Banter", soundResourceName: "GreatBanter.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "How neat is that?", soundResourceName: "HowNeatIsThat.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Dats pretty neat!", soundResourceName: "DatsPrettyNeat.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Milk (1)", soundResourceName: "HeNeedsSomeMilk.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Milk (2)", soundResourceName: "GetHimSomeMilk.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Meow &@%$", soundResourceName: "MeowBitch.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "Meow the &@%$", soundResourceName: "MeowTheFuck.mp3", iconResourceName:  "Markiplier", isFavorite: false),
    Sound(labelText: "Graphics!", soundResourceName: "ThemGraphicsTho.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "TOASTY!", soundResourceName: "TOASTY.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Barking Old Man", soundResourceName: "BarkingOldMan.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Cheesecake", soundResourceName: "ILoveCheesecake.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Profanity", soundResourceName: "Profanity.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Trump's Small Loan", soundResourceName: "SmallLoan.mp3", iconResourceName:  "Donald Trump", isFavorite: false),
    Sound(labelText: "Knowledge", soundResourceName: "MaterialisticThingsKnowledge.mp3", iconResourceName:  "KnowledgeGuy", isFavorite: false),
    Sound(labelText: "Lamborghini", soundResourceName: "NewLambo.mp3", iconResourceName:  "KnowledgeGuy", isFavorite: false),
    Sound(labelText: "Bookshelves", soundResourceName: "Bookshelves.mp3", iconResourceName:  "KnowledgeGuy", isFavorite: false),
    Sound(labelText: "JUST DO IT!", soundResourceName: "JustDoIt.mp3", iconResourceName:  "JustDoIt", isFavorite: false),
    Sound(labelText: "Ranting Kid", soundResourceName: "DoYouHonestly.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "In the Neck", soundResourceName: "FuckYouInTheNeck.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Suddenly Pineapples", soundResourceName: "Pineapples.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "I like trains", soundResourceName: "Trains.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Why the %&@# you lying?", soundResourceName: "WhyTheFuck.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Why you always lying?", soundResourceName: "WhyYouAlwaysLying.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Get your teeth straight", soundResourceName: "STFUAndGetYourTeethStraight.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Iridocyclitis", soundResourceName: "Iridocyclitis.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Pretty Good", soundResourceName: "iDubbbzPrettyGood.mp3", iconResourceName:  "idubbbz", isFavorite: false),
    Sound(labelText: "nope.avi", soundResourceName: "NopeAVI.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Can't Believe", soundResourceName: "CantBelieve.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "McFallen", soundResourceName: "McFallen.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Sorry I've McFallen", soundResourceName: "SorryMcFallen.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "McScuse Me *$%&#?", soundResourceName: "McScuseMeBitch.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Throat Punched", soundResourceName: "ThroatPunched.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Civil Rights", soundResourceName: "CivilRights.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Time to Stop", soundResourceName: "TimeToStop.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Time to Stop (Full)", soundResourceName: "TimeToStopFull.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Quit It!", soundResourceName: "TGuy1.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Too Pissed", soundResourceName: "TGuy2.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Fish Sticks", soundResourceName: "TGuy3.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Bird", soundResourceName: "TGuy4.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Holy S%$@", soundResourceName: "TGuy5.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Couins", soundResourceName: "JonCouins.mp3", iconResourceName:  "JonTron", isFavorite: false),
    Sound(labelText: "Holy S%$@", soundResourceName: "JonHolyShit.mp3", iconResourceName:  "JonTron", isFavorite: false),
    Sound(labelText: "Damn Daniel (1)", soundResourceName: "dd1.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Damn Daniel (2)", soundResourceName: "dd2.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Damn Daniel (3)", soundResourceName: "dd3.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "White Vans (1)", soundResourceName: "backatit1.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "White Vans (2)", soundResourceName: "whitevans.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Ethan Bradberry", soundResourceName: "ethanbradberry.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Hamburger plz (1)", soundResourceName: "hamburgerpls.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Hamburger plz (2)", soundResourceName: "hamburgerpls2.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Roasted", soundResourceName: "FFRoasted.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "NNYESSS", soundResourceName: "FFSalamanderYES.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Give Me the Succ", soundResourceName: "givemethesucc.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Hey b0ss (1)", soundResourceName: "heyb0ss1.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Hey b0ss (2)", soundResourceName: "heyb0ss2.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Hey b0ss (3)", soundResourceName: "b0sspizza.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "I have a cancer", soundResourceName: "ihaveacancer.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Pink Guy (1)", soundResourceName: "FFScream.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Pink Guy (2)", soundResourceName: "pinkguy.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Pink Guy (3)", soundResourceName: "pinkguy1.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Horrible", soundResourceName: "MRHorrible.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Box", soundResourceName: "box.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Made a Box", soundResourceName: "MRMadeABox.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Oh no!", soundResourceName: "MROHNO.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Get out of here!", soundResourceName: "MRGetOutOfHere.mp3", iconResourceName:  "Dahead", isFavorite: false),
    Sound(labelText: "Cough", soundResourceName: "h3h3 cough.mp3", iconResourceName:  "h3h3", isFavorite: false),
    Sound(labelText: "DURR PLANT", soundResourceName: "DURRPLANT.mp3", iconResourceName:  "IHateEverything", isFavorite: false),
    Sound(labelText: "NOOT NOOT", soundResourceName: "NOOT NOOT.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Wednesday", soundResourceName: "Wednesday.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "???", soundResourceName: "???.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Avocado", soundResourceName: "Fresh Avocado Vine.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Hai (Okay)", soundResourceName: "Hai (Okay).mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Lung buster", soundResourceName: "lung buster.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "WTF", soundResourceName: "JonWTF.mp3", iconResourceName:  "JonTron", isFavorite: false),
    Sound(labelText: "MY FAVORITE", soundResourceName: "OH MY FAVORITE.mp3", iconResourceName:  "JonTron", isFavorite: false),
    Sound(labelText: "Boy-", soundResourceName: "Boy if you dont -.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Crazy Trickshot", soundResourceName: "CrazyTrickshot1.mp3", iconResourceName:  "MerkMusic", isFavorite: false),
    Sound(labelText: "Trickshot Stutter", soundResourceName: "TrickshotStutter.mp3", iconResourceName:  "MerkMusic", isFavorite: false),
    Sound(labelText: "DOUBLE BANK", soundResourceName: "DOUBLEBANK.mp3", iconResourceName:  "MerkMusic", isFavorite: false),
    Sound(labelText: "South Dakota", soundResourceName: "SouthDakota.mp3", iconResourceName:  "MerkMusic", isFavorite: false),
    Sound(labelText: "Woah Internet", soundResourceName: "WoahInternet.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "I know that B&^@!", soundResourceName: "OhShitIKnowThatBitch.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Funny noise", soundResourceName: "FunnyNoise.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Wacky Stuff", soundResourceName: "Wacky.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Jungle Gym", soundResourceName: "JungleGym.mp3", iconResourceName:  "BRogers", isFavorite: false),
    Sound(labelText: "Bad Choices", soundResourceName: "BadChoices.mp3", iconResourceName:  "BRogers", isFavorite: false),
    Sound(labelText: "Bad for your eye", soundResourceName: "Blind.mp3", iconResourceName:  "BRogers", isFavorite: false),
    Sound(labelText: "Rash Ointment", soundResourceName: "Rash.mp3", iconResourceName:  "BRogers", isFavorite: false),
    Sound(labelText: "*ringing*", soundResourceName: "HighPitchedEarRinging.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Wizard Harry", soundResourceName: "Wizard.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "dat boi", soundResourceName: "datboi.mp3", iconResourceName:  "DatBoi", isFavorite: false),
    Sound(labelText: "oh s%^@ wuddup", soundResourceName: "oh shit waddup.mp3", iconResourceName:  "DatBoi", isFavorite: false),
    Sound(labelText: "wuddup", soundResourceName: "wuddup.mp3", iconResourceName:  "DatBoi", isFavorite: false),
    Sound(labelText: "here come dat boi", soundResourceName: "herecomedatboisong.mp3", iconResourceName:  "DatBoi", isFavorite: false),
    Sound(labelText: "Legitness", soundResourceName: "thatwaslegitness.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "*censor*", soundResourceName: "Censor.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Another one", soundResourceName: "DJAnotherOne.mp3", iconResourceName:  "DJ", isFavorite: false),
    Sound(labelText: "Bless up", soundResourceName: "DJBlessUp.mp3", iconResourceName:  "DJ", isFavorite: false),
    Sound(labelText: "Lion", soundResourceName: "DJLion.mp3", iconResourceName:  "DJ", isFavorite: false),
    Sound(labelText: "Critical Stop", soundResourceName: "Windows XP Critical Stop.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Exclamation", soundResourceName: "Windows XP Exclamation.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Error", soundResourceName: "Windows XP Error.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Windows XP Death", soundResourceName: "Windows XP Deathh.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "XP Ear Raep", soundResourceName: "XP Ear Rape.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Vista", soundResourceName: "Vista.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Scarce", soundResourceName: "Scarce.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Robot Fan Fiction", soundResourceName: "Robot Fan fiction.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Robots have no soul", soundResourceName: "Robots have no soul.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Trash", soundResourceName: "Trash.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "OH YEAH", soundResourceName: "Oh yeah.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Ha Goteem", soundResourceName: "Hagoteem frank.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Nice T#@*%! (full)", soundResourceName: "Titties full.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Nice T#@*%!", soundResourceName: "titties.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "America is Great", soundResourceName: "America is Great.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "D!#*s out (1)", soundResourceName: "DicksOut1.mp3", iconResourceName:  "Harambe Icon", isFavorite: false),
    Sound(labelText: "D!#*s out (2)", soundResourceName: "DicksOut2.mp3", iconResourceName:  "Harambe Icon", isFavorite: false),
    Sound(labelText: "Bass Drop for Harambe", soundResourceName: "BASS DROP FOR HARAMBE.mp3", iconResourceName:  "Harambe Icon", isFavorite: false),
    Sound(labelText: "Dial Up Modem", soundResourceName: "Dial Up.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "I'm bi", soundResourceName: "I'm bi you're bi.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Genders", soundResourceName: "There are 3 genders.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Cresaunt", soundResourceName: "Cresaunt.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Ememy Spotted", soundResourceName: "ememy spotted.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Ememy UAV spotted", soundResourceName: "Heads up, enemy UAV spotted!.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Mission Failed", soundResourceName: "Mission failed we'll get em next time Sound Effect (NO MUSIC).mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "If If Crash", soundResourceName: "IF IF Crash.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Obama If", soundResourceName: "Obama IF.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Chicken Tendies", soundResourceName: "Chicken Tendies.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "You Played Yourself", soundResourceName: "Congratulations, you played yourself.mp3", iconResourceName:  "DJ", isFavorite: false),
    Sound(labelText: "I have depression", soundResourceName: "Depression idubbbz.mp3", iconResourceName:  "idubbbz", isFavorite: false),
    Sound(labelText: "I have Osteoporosis", soundResourceName: "I have OS idubbbz.mp3", iconResourceName:  "idubbbz", isFavorite: false),
    Sound(labelText: "That's pretty good!", soundResourceName: "iDubbz - Hey, that's pretty good!.mp3", iconResourceName:  "idubbbz", isFavorite: false),
    Sound(labelText: "Michael Jordan", soundResourceName: "Michael Jordan.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Get some help", soundResourceName: "Get some help.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Mountain Dew", soundResourceName: "Mountain Dew.mp3", iconResourceName:  "TourettesGuy", isFavorite: false),
    Sound(labelText: "Turn Up", soundResourceName: "Turn up.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Testicle", soundResourceName: "Testicle.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Speed", soundResourceName: "speed.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "SLAMMING", soundResourceName: "SLAMMING ethan.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Mr. Krabs", soundResourceName: "mr krabs.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "It's your boi", soundResourceName: "Skinny Penis.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "They ask you how you are", soundResourceName: "They ask you how you are and you just have to say that you're fine Sound Effect.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "What's a Dank Meme?", soundResourceName: "What's a Dank Meme?.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Gay", soundResourceName: "Gay.mp3", iconResourceName:  "idubbbz", isFavorite: false),
    Sound(labelText: "A Chair", soundResourceName: "A Chair!.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Ballsack", soundResourceName: "Ballsack.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Bigmac", soundResourceName: "Bigmac.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Butterfly Cop", soundResourceName: "Butterfly Cop.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Cereal", soundResourceName: "Cereal.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Chegg 1", soundResourceName: "Chegg 1.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Chegg 2", soundResourceName: "Chegg 2.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "DAB", soundResourceName: "DAB.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "You want?", soundResourceName: "Dick.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Drive Thru", soundResourceName: "Drive Thru.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "DVD", soundResourceName: "DVD.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Familiar Faces", soundResourceName: "Familiar Faces.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Final Countdown", soundResourceName: "Final Countdown.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Cancer", soundResourceName: "FFCancer.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Cutting tips", soundResourceName: "FFCut.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Edgy", soundResourceName: "FFEdgy.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Kill Me Now!", soundResourceName: "FFKIll Me Now.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Memes 1", soundResourceName: "FFMemes 1.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Memes 2", soundResourceName: "FFMemes 2.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Memes 3", soundResourceName: "FFMemes 3.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Pranked", soundResourceName: "FFPranked.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Two for the pink", soundResourceName: "FFTwoForThePink.mp3", iconResourceName:  "Frank3", isFavorite: false),
    Sound(labelText: "Fuck my Cat", soundResourceName: "Fuck my Cat.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Ghuhhh", soundResourceName: "Ghuhhh.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "GTA", soundResourceName: "GTA.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "I Love Cheesecake", soundResourceName: "I Love Cheesecake.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "ISIS", soundResourceName: "ISIS.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Just Chillin", soundResourceName: "Just Chillin.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Fast as !@#$", soundResourceName: "Keemstar Fast as Fuck.mp3", iconResourceName:  "Keemstar", isFavorite: false),
    Sound(labelText: "Life is Crazy", soundResourceName: "Life is Crazy.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Minecraft", soundResourceName: "Minecraft.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Noises", soundResourceName: "Noises.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Obama Bee Movie", soundResourceName: "Obama Bee Movie.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Obama Out", soundResourceName: "Obama Out.mp3",
        iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Yeet (Dank)", soundResourceName: "Yeet (Dank).mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Pokemon GO to the Polls", soundResourceName: "Pokemon GO to the Polls.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Rare Camel", soundResourceName: "Rare Camel.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Roast 1", soundResourceName: "Roast 1.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Roast 2", soundResourceName: "Roast 2.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Roast 3", soundResourceName: "Roast 3.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Roast 4", soundResourceName: "Roast 4.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Roblox Scream", soundResourceName: "Roblox Scream.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Samurai", soundResourceName: "Samurai.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Scared", soundResourceName: "Scared.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "She Farted on My D!@#", soundResourceName: "She Farted on My Dick.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "She Farted on My D!@# (Full Song)", soundResourceName: "She Farted on My Dick (Full Song).mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Spank 1", soundResourceName: "Spank 1.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Spank 2", soundResourceName: "Spank 2.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Stabbers", soundResourceName: "Stabbers.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Suh Dude", soundResourceName: "Suh Dude.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Sure about that", soundResourceName: "Sure about that.mp3", iconResourceName:  "Cena", isFavorite: false),
    Sound(labelText: "Tater Tots", soundResourceName: "Tater Tots.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Thirsty Thursday", soundResourceName: "Thirsty Thursday.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Trains", soundResourceName: "videogamedunkey Trains.mp3", iconResourceName:  "videogamedunkey", isFavorite: false),
    Sound(labelText: "Wake me up", soundResourceName: "Wake me Up.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Watch Your Jet", soundResourceName: "Watch Your Jet.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Yeah Boi", soundResourceName: "Yeah Boi.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Yeet", soundResourceName: "Yeet.mp3", iconResourceName:  "Vine", isFavorite: false),
    Sound(labelText: "Boneless Pizza (Full)", soundResourceName: "Boneless Pizza (Full).mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Boneless Pizza", soundResourceName: "Lemme get uhhh.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Boneless Pizza (2)", soundResourceName: "Lemme get that pizza BONELESS.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Two Liter Machine Broke", soundResourceName: "Two Liter Machine Broke.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "%@$# you mean 🅱️", soundResourceName: "The fuck you mean B.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Hella Bread (Full)", soundResourceName: "Hella Bread (Full).mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "United Bank of MONEY", soundResourceName: "United Bank of MONEY.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "HELLA BREAD", soundResourceName: "HELLA BREAD.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Italian Sub", soundResourceName: "Italian Sub.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Swear on your Timbs", soundResourceName: "Timbs.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Genderflux", soundResourceName: "Genderflux.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Gender Binary SYSTEM", soundResourceName: "Gender Binary SYSTEM.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Food Services", soundResourceName: "Food Services.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "Chicken Biscuit", soundResourceName: "Chicken Biscuit.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "YEEZY", soundResourceName: "YEEZY.mp3", iconResourceName:  "akuaku", isFavorite: false),
    Sound(labelText: "We are number one (Dank)", soundResourceName: "Number One.mp3", iconResourceName:  "NumberOne", isFavorite: false),
    Sound(labelText: "Apple Sauce", soundResourceName: "Apple Sauce.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Get out the way", soundResourceName: "Get out the way.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Ban Hammer", soundResourceName: "BANNED.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Be Gone Thot", soundResourceName: "Be Gone Thot.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Beans", soundResourceName: "Beans.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Biz's B-Day", soundResourceName: "Biz's B-Day.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Biz Dropping Fire", soundResourceName: "Biz's Dropping Fire.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Danimals Crunchers", soundResourceName: "Danimals Crunchers.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Empty", soundResourceName: "Empty.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Flute (Ear rape)", soundResourceName: "Flute.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Good Mountain Dew", soundResourceName: "Good Mountain Dew.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Hey 🅱️eter (1)", soundResourceName: "Hey Beter 1.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Hey 🅱️eter (2)", soundResourceName: "Hey Beter 2.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Hey 🅱️eter (3)", soundResourceName: "Hey Beter 3.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "I'm a Bird", soundResourceName: "I'm a Bird.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Interior Crododile", soundResourceName: "Interior Crocodile.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Jellybeans", soundResourceName: "Jellybeans.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Grandpa.exe", soundResourceName: "Kill Em.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "LEAN 😂💯", soundResourceName: "lean.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Minecraft - Look at Me", soundResourceName: "Minecraft - Look at Me.mp3", iconResourceName:  "Minecraft", isFavorite: false),
    Sound(labelText: "Minecraft - Mask Off", soundResourceName: "Minecraft - Mask Off.mp3", iconResourceName:  "Minecraft", isFavorite: false),
    Sound(labelText: "Minecraft - Water", soundResourceName: "Minecraft - Water.mp3", iconResourceName:  "Minecraft", isFavorite: false),
    Sound(labelText: "Minecraft pr0n", soundResourceName: "Minecraft Pr0n.mp3", iconResourceName:  "Minecraft", isFavorite: false),
    Sound(labelText: "XXXSENSATION", soundResourceName: "XXXSENSATION.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Ocean Man (Ear Rape)", soundResourceName: "Ocean Man.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Pizza Unboxing", soundResourceName: "Pizza.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Roast", soundResourceName: "Roast.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "SUCC", soundResourceName: "SUCC.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Traps are gay", soundResourceName: "Traps.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Falling Tree", soundResourceName: "Tree.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "WAKE ME UP (MS Bob)", soundResourceName: "WAKE ME UP - Microsoft Bob.mp3", iconResourceName:  "Generic", isFavorite: false),
    Sound(labelText: "Y'all mind if I hit that", soundResourceName: "Yall Mind if I hit that.mp3", iconResourceName:  "Instagram", isFavorite: false),
    Sound(labelText: "Michael Jackson", soundResourceName: "jackson_roast.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "Empty", soundResourceName: "empty.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Saturdays", soundResourceName: "saturdays.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Mickey Mouse (NSFW)", soundResourceName: "mickey_mouse.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Claw Game Ear Rape", soundResourceName: "claw_game.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Tree", soundResourceName: "tree.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: ">tfw no cereal", soundResourceName: ">tfwnocereal.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Jew Rap", soundResourceName: "https://soundcloud.com/ss7n/hava", iconResourceName:  "link", isFavorite: false),
    Sound(labelText: "Basketball", soundResourceName: "basketball.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Bill Nye (Ear Rape)", soundResourceName: "bill_nye.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Goat Rape", soundResourceName: "chompy.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "5 Gum", soundResourceName: "cigarette.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Win or Cringe?", soundResourceName: "cringe 1.mov", iconResourceName:  "player", isFavorite: false),
    Sound(labelText: "Teacher Dab", soundResourceName: "dab.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Screaming Dear (Video)", soundResourceName: "deer.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Horse Rekt", soundResourceName: "horse.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Spell ICUP", soundResourceName: "ICUP.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Macaroni Man", soundResourceName: "macaroni.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Minecraft Trickshot (FAKE)", soundResourceName: "minecraft_arrow.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "WARNING: Cringe", soundResourceName: "minecraft_cringe.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Money Shot", soundResourceName: "money_shot.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rekt Montage 1", soundResourceName: "montage 1.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rekt Montage 2", soundResourceName: "montage 2.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rekt Montage 3", soundResourceName: "montage 3.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rekt Montage 4", soundResourceName: "montage 4.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rekt Montage 5", soundResourceName: "montage 5.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Noice", soundResourceName: "noice.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Oxy Product (NSFW)", soundResourceName: "oxy clean.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Ball Race (Satisfying)", soundResourceName: "ball_race.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Prapy John", soundResourceName: "papa_johns.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Rawr xD ;3", soundResourceName: "rawr xD.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Snakes Have Legs", soundResourceName: "snakes_have_legs.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Traps are Gay", soundResourceName: "Traps are gay.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Woody Backstory", soundResourceName: "Andy Senpai.mp3", iconResourceName: "Generic", isFavorite: false),
    Sound(labelText: "Woody.gif", soundResourceName: "woody.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Minecraft pr0n", soundResourceName: "minecraft pr0n.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Two Genders", soundResourceName: "Two Genders.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Grilled Cheese", soundResourceName: "grilled_cheese.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Eat a D***", soundResourceName: "eat_a_dick.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Pizza Unboxing 1", soundResourceName: "pizza 1.nov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "Pizza Unboxing 2", soundResourceName: "pizza 2.mov", iconResourceName: "player", isFavorite: false),
    Sound(labelText: "XXXSENSATION (Montage)", soundResourceName: "xxx_clean.mov", iconResourceName: "player", isFavorite: false)
    
]

var soundContainers = [sounds]

//var pageBlank = [
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//    Sound(labelText: "", soundResourceName: "", iconResourceName:  "", isFavorite: false),
//]
